# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pasive_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.zCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.zCheck.setObjectName("zCheck")
        self.gridLayout.addWidget(self.zCheck, 2, 1, 1, 1)
        self.xCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.xCheck.setChecked(True)
        self.xCheck.setObjectName("xCheck")
        self.gridLayout.addWidget(self.xCheck, 2, 0, 1, 1)
        self.alphaVelCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.alphaVelCheck.setObjectName("alphaVelCheck")
        self.gridLayout.addWidget(self.alphaVelCheck, 3, 2, 1, 1)
        self.zVelCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.zVelCheck.setObjectName("zVelCheck")
        self.gridLayout.addWidget(self.zVelCheck, 3, 1, 1, 1)
        self.xVelCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.xVelCheck.setChecked(True)
        self.xVelCheck.setObjectName("xVelCheck")
        self.gridLayout.addWidget(self.xVelCheck, 3, 0, 1, 1)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 3)
        self.alphaCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.alphaCheck.setObjectName("alphaCheck")
        self.gridLayout.addWidget(self.alphaCheck, 2, 2, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zCheck.setText(_translate("MainWindow", "Z"))
        self.xCheck.setText(_translate("MainWindow", "X"))
        self.alphaVelCheck.setText(_translate("MainWindow", "Alpha vel"))
        self.zVelCheck.setText(_translate("MainWindow", "Z vel"))
        self.xVelCheck.setText(_translate("MainWindow", "X vel"))
        self.alphaCheck.setText(_translate("MainWindow", "Alpha"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
from pyqtgraph import PlotWidget
