# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'func_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 497)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 3, 1, 1, 1)
        self.function_choice = QtWidgets.QComboBox(Dialog)
        self.function_choice.setObjectName("function_choice")
        self.function_choice.addItem("")
        self.function_choice.addItem("")
        self.function_choice.addItem("")
        self.function_choice.addItem("")
        self.function_choice.addItem("")
        self.gridLayout.addWidget(self.function_choice, 0, 1, 1, 3)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 1, 1, 3)
        self.editButton = QtWidgets.QPushButton(Dialog)
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(Dialog)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 3, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 2, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.property_choice = QtWidgets.QComboBox(Dialog)
        self.property_choice.setObjectName("property_choice")
        self.property_choice.addItem("")
        self.property_choice.addItem("")
        self.property_choice.addItem("")
        self.gridLayout.addWidget(self.property_choice, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.function_choice.setItemText(0, _translate("Dialog", "Lip-to-edge distance"))
        self.function_choice.setItemText(1, _translate("Dialog", "Incidence angle"))
        self.function_choice.setItemText(2, _translate("Dialog", "Jet Offset"))
        self.function_choice.setItemText(3, _translate("Dialog", "Flow Q"))
        self.function_choice.setItemText(4, _translate("Dialog", "Notes"))
        self.editButton.setText(_translate("Dialog", "Edit"))
        self.label_2.setText(_translate("Dialog", "Property"))
        self.deleteButton.setText(_translate("Dialog", "Delete"))
        self.label.setText(_translate("Dialog", "Function"))
        self.property_choice.setItemText(0, _translate("Dialog", "Points"))
        self.property_choice.setItemText(1, _translate("Dialog", "Vibratos"))
        self.property_choice.setItemText(2, _translate("Dialog", "Filters"))
        self.label_3.setText(_translate("Dialog", "Values"))
