# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vibrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(317, 254)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.time_i = QtWidgets.QDoubleSpinBox(Dialog)
        self.time_i.setObjectName("time_i")
        self.gridLayout.addWidget(self.time_i, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.duration = QtWidgets.QDoubleSpinBox(Dialog)
        self.duration.setObjectName("duration")
        self.gridLayout.addWidget(self.duration, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.amp = QtWidgets.QDoubleSpinBox(Dialog)
        self.amp.setObjectName("amp")
        self.gridLayout.addWidget(self.amp, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.freq = QtWidgets.QDoubleSpinBox(Dialog)
        self.freq.setObjectName("freq")
        self.gridLayout.addWidget(self.freq, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.window_v = QtWidgets.QComboBox(Dialog)
        self.window_v.setObjectName("window_v")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.window_v.addItem("")
        self.gridLayout.addWidget(self.window_v, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Starting at"))
        self.label_2.setText(_translate("Dialog", "Duration"))
        self.label_3.setText(_translate("Dialog", "Amplitude"))
        self.label_4.setText(_translate("Dialog", "Frequency"))
        self.label_5.setText(_translate("Dialog", "Window"))
        self.window_v.setItemText(0, _translate("Dialog", "rect"))
        self.window_v.setItemText(1, _translate("Dialog", "triangular"))
        self.window_v.setItemText(2, _translate("Dialog", "blackman"))
        self.window_v.setItemText(3, _translate("Dialog", "hamming"))
        self.window_v.setItemText(4, _translate("Dialog", "hanning"))
        self.window_v.setItemText(5, _translate("Dialog", "kaiser1"))
        self.window_v.setItemText(6, _translate("Dialog", "kaiser2"))
        self.window_v.setItemText(7, _translate("Dialog", "kaiser3"))
        self.window_v.setItemText(8, _translate("Dialog", "kaiser4"))
