# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'axis_control_loop_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.kp_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.kp_value.setDecimals(5)
        self.kp_value.setObjectName("kp_value")
        self.gridLayout.addWidget(self.kp_value, 0, 1, 1, 1)
        self.kp_vel_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.kp_vel_value.setDecimals(5)
        self.kp_vel_value.setObjectName("kp_vel_value")
        self.gridLayout.addWidget(self.kp_vel_value, 0, 3, 1, 1)
        self.prop_value = QtWidgets.QSpinBox(Dialog)
        self.prop_value.setMaximum(50)
        self.prop_value.setObjectName("prop_value")
        self.gridLayout.addWidget(self.prop_value, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.acc_value = QtWidgets.QSpinBox(Dialog)
        self.acc_value.setMinimum(1)
        self.acc_value.setMaximum(5000)
        self.acc_value.setProperty("value", 400)
        self.acc_value.setObjectName("acc_value")
        self.gridLayout.addWidget(self.acc_value, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 2)
        self.kd_vel_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.kd_vel_value.setDecimals(5)
        self.kd_vel_value.setObjectName("kd_vel_value")
        self.gridLayout.addWidget(self.kd_vel_value, 2, 3, 1, 1)
        self.dec_value = QtWidgets.QSpinBox(Dialog)
        self.dec_value.setMinimum(1)
        self.dec_value.setMaximum(5000)
        self.dec_value.setProperty("value", 400)
        self.dec_value.setObjectName("dec_value")
        self.gridLayout.addWidget(self.dec_value, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.ki_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.ki_value.setDecimals(5)
        self.ki_value.setObjectName("ki_value")
        self.gridLayout.addWidget(self.ki_value, 1, 1, 1, 1)
        self.kd_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.kd_value.setDecimals(5)
        self.kd_value.setObjectName("kd_value")
        self.gridLayout.addWidget(self.kd_value, 2, 1, 1, 1)
        self.ki_vel_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.ki_vel_value.setDecimals(5)
        self.ki_vel_value.setObjectName("ki_vel_value")
        self.gridLayout.addWidget(self.ki_vel_value, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_12.setText(_translate("Dialog", "Kd_vel"))
        self.label_6.setText(_translate("Dialog", "Proportional Coef"))
        self.label_2.setText(_translate("Dialog", "Ki"))
        self.label_5.setText(_translate("Dialog", "Deceleration"))
        self.label_9.setText(_translate("Dialog", "Kp_vel"))
        self.label.setText(_translate("Dialog", "Kp"))
        self.label_4.setText(_translate("Dialog", "Acceleration"))
        self.label_3.setText(_translate("Dialog", "Kd"))
        self.label_8.setText(_translate("Dialog", "Ki_vel"))
