# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 356)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.var_comboBox = QtWidgets.QComboBox(Dialog)
        self.var_comboBox.setObjectName("var_comboBox")
        self.var_comboBox.addItem("")
        self.var_comboBox.addItem("")
        self.var_comboBox.addItem("")
        self.gridLayout.addWidget(self.var_comboBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.loop_comboBox = QtWidgets.QComboBox(Dialog)
        self.loop_comboBox.setObjectName("loop_comboBox")
        self.loop_comboBox.addItem("")
        self.loop_comboBox.addItem("")
        self.gridLayout.addWidget(self.loop_comboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.kp_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.kp_spinbox.setMaximum(9999.0)
        self.kp_spinbox.setProperty("value", 345.0)
        self.kp_spinbox.setObjectName("kp_spinbox")
        self.gridLayout.addWidget(self.kp_spinbox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.ki_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.ki_spinbox.setMaximum(9999.0)
        self.ki_spinbox.setObjectName("ki_spinbox")
        self.gridLayout.addWidget(self.ki_spinbox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.kd_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.kd_spinbox.setMaximum(9999.0)
        self.kd_spinbox.setProperty("value", 2816.0)
        self.kd_spinbox.setObjectName("kd_spinbox")
        self.gridLayout.addWidget(self.kd_spinbox, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Var. to control:"))
        self.var_comboBox.setItemText(0, _translate("Dialog", "Mass Flow"))
        self.var_comboBox.setItemText(1, _translate("Dialog", "Volumetric Flow"))
        self.var_comboBox.setItemText(2, _translate("Dialog", "Pressure"))
        self.label_5.setText(_translate("Dialog", "Control Loop:"))
        self.loop_comboBox.setItemText(0, _translate("Dialog", "PDF"))
        self.loop_comboBox.setItemText(1, _translate("Dialog", "PD2I"))
        self.label.setText(_translate("Dialog", "Kp:"))
        self.label_2.setText(_translate("Dialog", "Ki:"))
        self.label_3.setText(_translate("Dialog", "Kd:"))
