# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Plot = QtWidgets.QAction(MainWindow)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.actionX = QtWidgets.QAction(MainWindow)
        self.actionX.setCheckable(True)
        self.actionX.setObjectName("actionX")
        self.actionX_ref = QtWidgets.QAction(MainWindow)
        self.actionX_ref.setCheckable(True)
        self.actionX_ref.setObjectName("actionX_ref")
        self.actionZ = QtWidgets.QAction(MainWindow)
        self.actionZ.setCheckable(True)
        self.actionZ.setObjectName("actionZ")
        self.actionZ_ref = QtWidgets.QAction(MainWindow)
        self.actionZ_ref.setCheckable(True)
        self.actionZ_ref.setObjectName("actionZ_ref")
        self.actionAlpha = QtWidgets.QAction(MainWindow)
        self.actionAlpha.setCheckable(True)
        self.actionAlpha.setObjectName("actionAlpha")
        self.actionAlpha_ref = QtWidgets.QAction(MainWindow)
        self.actionAlpha_ref.setCheckable(True)
        self.actionAlpha_ref.setObjectName("actionAlpha_ref")
        self.menuFile.addAction(self.actionSave_Plot)
        self.menuEdit.addAction(self.actionX)
        self.menuEdit.addAction(self.actionX_ref)
        self.menuEdit.addAction(self.actionZ)
        self.menuEdit.addAction(self.actionZ_ref)
        self.menuEdit.addAction(self.actionAlpha)
        self.menuEdit.addAction(self.actionAlpha_ref)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save Plot"))
        self.actionX.setText(_translate("MainWindow", "X"))
        self.actionX_ref.setText(_translate("MainWindow", "X_ref"))
        self.actionZ.setText(_translate("MainWindow", "Z"))
        self.actionZ_ref.setText(_translate("MainWindow", "Z_ref"))
        self.actionAlpha.setText(_translate("MainWindow", "Alpha"))
        self.actionAlpha_ref.setText(_translate("MainWindow", "Alpha_ref"))
from pyqtgraph import PlotWidget
