# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_plot_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 1, 1, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xButton = QtWidgets.QRadioButton(self.centralwidget)
        self.xButton.setChecked(True)
        self.xButton.setObjectName("xButton")
        self.horizontalLayout.addWidget(self.xButton)
        self.zButton = QtWidgets.QRadioButton(self.centralwidget)
        self.zButton.setObjectName("zButton")
        self.horizontalLayout.addWidget(self.zButton)
        self.alphaButton = QtWidgets.QRadioButton(self.centralwidget)
        self.alphaButton.setObjectName("alphaButton")
        self.horizontalLayout.addWidget(self.alphaButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.recordCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.recordCheckBox.setObjectName("recordCheckBox")
        self.gridLayout.addWidget(self.recordCheckBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Plot = QtWidgets.QAction(MainWindow)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.menuFile.addAction(self.actionSave_Plot)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.xButton.setText(_translate("MainWindow", "X"))
        self.zButton.setText(_translate("MainWindow", "Z"))
        self.alphaButton.setText(_translate("MainWindow", "Alpha"))
        self.recordCheckBox.setText(_translate("MainWindow", "Record data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save Plot"))
from pyqtgraph import PlotWidget
